# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: replacemerepo
  tag: replacemetag
  # repository: tobespc/groceryfrontend
  # tag: latest
  pullPolicy: Always
livenessProbe:
  initialDelaySeconds: 3000
  periodSeconds: 1000
service:
  name: node
  type: NodePort
  servicePort: 3000

