apiVersion: v1
kind: Service
metadata:
  name: groceryfrontend
spec:
  type: NodePort
  selector:
    app: component-groceryfrontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: groceryfrontend
spec:
  selector:
    matchLabels:
      app: component-groceryfrontend
  template:
    metadata:
      labels:
        app: component-groceryfrontend
    spec:
      containers:
      - name: grocery-frontend
        image: tobespc/groceryfrontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000